services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./app.py user password db jobs jobs.csv job_id,job_name 
              && python3 ./app.py user password db hired_employees hired_employees.csv id,name,datetime,department_id,job_id
              && python3 ./app.py user password db departments departments.csv id,department "
  
    depends_on:
      - mysql
    networks:
      red_web:
        ipv4_address: 192.168.10.10
      red_interna:
        ipv4_address: 192.168.20.10



  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      red_interna:
        ipv4_address: 192.168.20.20
    hostname: servidor_mysql



networks:
    red_web:
        ipam:
            config:
              - subnet: 192.168.10.0/24
    red_interna:
        ipam:
            config:
              - subnet: 192.168.20.0/24
